// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekcvjyqcsxmkwyemtfag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrY3ZqeXFjc3hta3d5ZW10ZmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDY1ODAsImV4cCI6MjA2NjUyMjU4MH0.w26spqaNjcMN09H2qG3YtxuKAUG_Tz73SPKRdIv7K7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);